* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :CLASS: unnumbered
  :END:
...\\

* RESULTS AND DISCUSSION
  :PROPERTIES:
  :CUSTOM_ID: results-and-discussion
  :CLASS: unnumbered
  :END:
*Figure1:*\\
Outline of work: HT-DFT Data Generation \(\rightarrow\) Descriptors and
correlations \(\rightarrow\) Surrogate ML Models (NN, RFR, GPR)
\(\rightarrow\) Inverse design using Genetic Algorithm \(\rightarrow\)
Validation of promising compounds.\\
*Figure2:*\\
Quick visualization of PBE data + correlations with descriptors
(reproduced from other paper?).\\
*Figure3:*\\
All surrogate ML model results:

- RMSE vs training set size for NN, RFR and GPR, using composition only,
  elemental only, and both together, for 3 properties: *decomposition
  energy, band gap, SLME*.

- Best RMSE values for each property for different ML techniques and
  different descriptors

- Parity plots for best ML models for each property

\\
*Figure4:*\\
Genetic algorithm results:

- Fitness score vs generation, stability only.

- Fitness score vs generation, stability + band gap.

- Fitness score vs generation, stability + band gap + SLME.

- Performance of GA with NN/GPR/RFR and with comp/elem/comp+elem.\\

*Figure5:*\\
Validation using new DFT calculations on 10 compositions in 4x4x4
supercell. DFT vs ML properties + band structure + absorption spectra.\\

** ...
   :PROPERTIES:
   :CUSTOM_ID: section
   :CLASS: unnumbered
   :END:
** ...
   :PROPERTIES:
   :CUSTOM_ID: section-1
   :CLASS: unnumbered
   :END:
** Summary
   :PROPERTIES:
   :CUSTOM_ID: summary
   :CLASS: unnumbered
   :END:
...\\

* METHODS
  :PROPERTIES:
  :CUSTOM_ID: methods
  :CLASS: unnumbered
  :END:
** DFT Details
   :PROPERTIES:
   :CUSTOM_ID: dft-details
   :CLASS: unnumbered
   :END:
...\\
*** TODO Chemical Featurization

** Surrogate Modeling Perovskite Properties
   :PROPERTIES:
   :CUSTOM_ID: surrogate-ml-models
   :CLASS: unnumbered
   :END:
*** Objectives
Our objectives are two fold:

First, we aim to accurately predict performance-relevant Perovskite
band gaps, decomposition energies, and Spectroscopically Limited Maximum
Efficiency (SLME).

We will follow a multi-fidelity approach, where the bulk of affordable
low level-of-theory data will inform and improve the extrapolative
ability of models trained on higher fidelity measurements.

Our fidelity hierarchy climbs from results obtained using a PBE
functional, to results obtained using an HSE functional, to
experimental results aggregated in literature [[cite:&almora-2020-devic-perfor]].

We aim to express these variables as functions of the Perovskite
composition. Schemes for incorporating structural information will be
developed in future work. Nevertheless, a strong understanding of the
influence of chemical composition on performance will continue to be a
priority as it is expected to aid in screening the combinatorial
chemical space for viable compounds based on both available precursors
and performance criteria.

Furthermore, chemical data can already be mined for a rich feature set
as previously discussed.

Second, we hope to better understand the average physical impacts
of 1) site-specific alloying and 2) using organic molecules in the
Perovskite superstructure.

These goals are not entirely separate from the first goal of
expressing various properties as functions of composition, but they
can be more simply approached as problems of addressing dependencies
in the data statistics. Our model development will test the hypothesis
that formula that fall within one of these classifications will share
some distributed qualities with others that fit their classification.

These are certainly not the only groups of dependent samples
potentially generated by these experiments, but they are the most
noticeable in the structure of the multi-fidelity sample set as we
have constructed it.
*** Considerations
We expect that perovskites of a given alloy class and of a given
hybrid-organic/inorganic status will perform significantly
differently, in all respects, to Perovskites of a another class or
status. By leveraging the even distribution of constituent compounds
in this sample set of Halide Perovskites, we can cast this problem as
a series of cross-validations for independently trained models.

A minimum of 3-fold cross-validation is performed for every set of
model parameters that is considered. 

Two separate cross validation schemes are employed at each stage of
the design process.

First, the sample set is shuffled once and split to mitigate the
models tendency to fit on sample order, then, stratified K-folds are
generated in manner consistent with the classification of each
sample. However, this fold is not used in a classification problem,
the regressor is trained on the subsets of each class, and it's
ability to extrapolate is independently metered on each validation
fold consisting of members of the other classes.

Second, the ability for a model trained on samples belonging to one
class/status to extrapolate to samples of another class/status is
tested as well. The samples again are shuffled and split. then the
training set is separated using a grouping K-fold split strategy (stratified? shuffled?)

Per architecture, a model is instantiated using the, in aggregate,
best performing parameters. These models are finally validated against
the test sets originally split off from the sample in *both their
extrapolative ability and consistency across groups.*

*** Model Optimization Details
The rigorous hyper-Parameter Optimization (HPO) of any feature
engineering and modeling pipeline is a problem discussed extensively
in the literature. HPO approaches can be broadly separated into
exhaustive and efficient optimization strategies
[[cite:&yang-2020-hyper-optim]]. We use a two-stage procedure for
selecting the best model parameters.

The first stage is an exhaustive grid-search over diversely sampled
parameter space. Each combination of parameters instantiates a model
which is then fit to each of a set of stratified training subsets
generated by a 3-fold cross-validation strategy. Every fitted model is
subsequently tested against the cross-validation test sets and a suite
of regression scoring metrics are applied simultaneously.

The scoring metrics we choose vary by model architecture. See summary tables.

The grid search is then narrowed to a high performance quadrant of the
search space by the model evaluator based on recommendations made by a
simple entropy minimization algorithm implemented in the "yogi"
supplementary package under the yogi.model_selection.butler module --
see documentation for the various grid-narrowing strategies available.

In general, the recommended grid quickly eliminates under-performing
settings based on the sample probability of a setting appearing in a
set of finalists according to the scoring rankings. The selection
score is additionally influenced by a weighted sum of the scoring
ranks allowing for considerably tuning of the selection criterion.
For best results, a few different grid spaces should be explored to
corroborate eliminations.

After the recommendation is made, the granularity of the grid is
increased in the remaining ambiguous parameters and the process is
repeated.

Additionally/Alternatively,

** Genetic Algorithm
   :PROPERTIES:
   :CUSTOM_ID: genetic-algorithm
   :CLASS: unnumbered
   :END:
...\\

* ACKNOWLEDGMENTS
  :PROPERTIES:
  :CUSTOM_ID: acknowledgments
  :CLASS: unnumbered
  :END:

We acknowledge funding from the US Department of Energy SunShot program
under contract #DOE DEEE005956. Use of the Center for Nanoscale
Materials, an Office of Science user facility, was supported by the U.S.
Department of Energy, Office of Science, Office of Basic Energy
Sciences, under Contract No. DE-AC02-06CH11357. We gratefully
acknowledge the computing resources provided on Bebop, a
high-performance computing cluster operated by the Laboratory Computing
Resource Center at Argonne National Laboratory. This research used
resources of the National Energy Research Scientific Computing Center, a
DOE Office of Science User Facility supported by the Office of Science
of the U.S. Department of Energy under Contract No. DE-AC02-05CH11231.
MYT would like to acknowledge support from the U.S. Department of
Energy, Office of Science, Office of Workforce Development for Teachers
and Scientists (WDTS) under the Science Undergraduate Laboratory
Internship (SULI) program. MJD was was supported by the U. S. Department
of Energy , Office of Basic Energy Sciences, Division of Chemical
Sciences, Geosciences, and Biosciences, under Contract No.
DE-AC02-06CH11357.

** Author Contributions
   :PROPERTIES:
   :CUSTOM_ID: author-contributions
   :CLASS: unnumbered
   :END:
M.K.Y.C., R.F.K. and A.M.K. conceived the idea. A.M.K., M.Y.T. and
F.G.S. performed the DFT computations. A.M.K. and M.J.D. trained ML
models. All authors contributed to the discussion and writing of the
manuscript.

** Data Availability
   :PROPERTIES:
   :CUSTOM_ID: data-availability
   :CLASS: unnumbered
   :END:
DFT data and ML models are available from the corresponding author upon
reasonable request.

** Additional Information
   :PROPERTIES:
   :CUSTOM_ID: additional-information
   :CLASS: unnumbered
   :END:
The authors declare no competing financial or non-financial interests.

Correspondence and requests for materials should be addressed to A.M.K.
(email:amannodi@purdue.edu).

* REFERENCES
  :PROPERTIES:
  :CUSTOM_ID: references
  :CLASS: unnumbered
  :END:
bibliographystyle:authordate1
bibliography:~/org/bibliotex/bibliotex.bib
